### ISSUE TITLE
Extract column as a []float64?

### ISSUE THREAD

**Issue by btracey** [tobgu/qframe#10]
I'm hoping to extract a column as a []float64, or a set of columns as a `*mat.Dense`. Is that possible?

**Comment by btracey** [comment]
Figured it out, sorry. Here's the algorithm for future reference

```
        cols := qf.ColumnNames()
	r := qf.Len()
	c := len(cols)
	m := mat.NewDense(r, c, nil)
	for i := range cols {
		fs := qf.MustFloatView(cols[i]).Slice()
		m.SetCol(i, fs)
	}
```

**Comment by tobgu** [comment]
Great! If you want to add convenience methods to qframe itself for integration with `mat` I'm all for it. Use the contrib pattern used for Gonum integration then to avoid forcing `mat` on users of QFrame that do not use `mat`.

I'm closing this issue now.
