### ISSUE TITLE
Iterate Over the given qframe

### ISSUE THREAD

**Issue by usmankb** [tobgu/qframe#12]
Any example which depicts how to iterate over the rows present in the qframe?

**Comment by tobgu** [comment]
Are you asking for some way to do something like a "map" over all rows receiving something like a `map[string]interface{}` in a callback for every row? There is no functionality like this.
I haven't seen the reason for it. Could you tell me what kind of problem you are trying to solve and perhaps I can offer an alternative way of doing it?

**Comment by tobgu** [comment]
OK, I would use `Apply` for that, see https://godoc.org/github.com/tobgu/qframe#example-QFrame--ApplyStrConcat for an example.

**Comment by tobgu** [comment]
Did you find functionality matching your use case? Can this be closed?

If not, `Eval` is another, slightly higher level concept than `Apply` that can be used for data transformation. There is a small comparison between `Apply` and `Eval` in the main README. If you have a specific example of what you want to achieve I can perhaps help sketching out how to do it.

**Comment by usmankb** [comment]
We can close this But I am actually looking for some way on how to check the duplicate values in the column.Can you help me with the sample snippet ?

**Comment by usmankb** [comment]
also sample snippets for Difference between two qframes,Dump the qframe to mysql tables will help me a lot.

**Comment by usmankb** [comment]
I have actually tried inserting my qframe to the mysql table but it is not inserting any rows to the db.

I have attache my sample snippet here can you please tell whats wrong?


        filename := "filepath"

	f, _ := os.Open(filename)

	body, _ := ioutil.ReadAll(f)

	f2:=(qframe.ReadCSV(strings.NewReader(string(body))))

	

	db, _ := sql.Open("mysql", "username@password@tcp(ipaddress:3306)/test")

	tx,_:=db.Begin()

	fmt.Println("start")

	fmt.Println(f2)

	err:=f2.ToSQL(tx,qsql.Table("sample table"),qsql.MySQL())

**Comment by tobgu** [comment]
Closing this now, please reopen if you have more information.
