### ISSUE TITLE
Load CSV with now header

### ISSUE THREAD

**Issue by javier-sanz** [tobgu/qframe#13]
There are cases when CSV files has not a header and column names are stored in another file (e.g. `LOAD DATA ` sentences). In pandas that is supported a follows:

```python
fileDf = pd.read_csv(fileName, header=None, names=header)
```
I would be great if qframe could support something like that.

**Comment by tobgu** [comment]
Sure, shouldn't be too difficult. You just need to add a new CSV config option and skip reading the header (https://github.com/tobgu/qframe/blob/master/internal/io/csv.go#L36) when headers have been supplied though config.

If you want to contribute this I'd be happy to help out and review it! It's probably the quickest way to get it done.

**Comment by javier-sanz** [comment]
Thanks @tobgu for you quick answer. Ok I can try to do the changes myself. Should I create the PR on this repo or fork a new repo and the merge it?

**Comment by tobgu** [comment]
Fork it to your own user and then make a PR back to this repo for merge or when you want feedback on what you've done.
