### ISSUE TITLE
Is there any plan to support time columns/types?

### ISSUE THREAD

**Issue by tappoz** [tobgu/qframe#14]
I can see that there is this `internal` package to deal with column types.
I can not find a `time.Time` implementation for the `icolumn.View` stuff, is there any plan to support this?

Would it be just a matter of adding the relevant code to the package `internal` or are there other places to change/complement?

I am basically trying to apply functions to a time column to change time-zones, then being able to filter the rows according to these time-zoned columns.

**Comment by tobgu** [comment]
Thanks for your question. Yes, I've definitely thought about adding proper support for time to make it easier to work with time series etc. I'd be lying if I said that is something planned for the near future though as I currently have very limited resources to work on this.

Adding a time type would estentially mean adding a new column type mean adding a type that implements the `Column` interface: https://github.com/tobgu/qframe/blob/master/internal/column/column.go#L11.
Then some code would be needed to actually create this type of columns based on input (date parsing etc.). I'd be super happy if this is something you would like to contribute and would help out pointing you in the right direction.

Meanwhile, if you want something up and running in the short term I can perhaps assist you in achieving what you want with one or a couple of helper columns if you just flesh out the use case you have and perhaps share any code you have so far.

**Comment by tappoz** [comment]
Thanks for these details. I am interested in adding this kind of functionality, but I need to negotiate this as I am doing it for work. Meanwhile I am trying to work around my problem using a slice of structs, not ideal but it works so I may be just using this solution while prototyping this MVP.

I am basically trying to filter the rows of the equivalent of a Pandas dataframe (in the Python world) via rules based on time-zones. I am dealing with 3 different data streams in:

- UTC,
- British Local Time and
- CET time-zones. 

Sometimes these timestamps represent the same hour/minute `HH:mm`, some other times they don't depending on the season (winter/summer) and the time-zone itself.

This is relevant because the data that needs to be produced as output is driven by "half-hour IDs" (1 to 48 in an entire day made of 24 hours). Due to the time-zone rules these "zoned IDs" sometimes have the same value, some other times they don't, but they represent indeed the same timestamp. 

I am doing these calculations as extra fields in the structs in the slice, however ideally they could be extra columns in the dataframe.
Thanks again for this library, it looks quite promising.

**Comment by tobgu** [comment]
WIthout knowing what your input data looks like and how you expect the output to look like here's what I'd suggest off the top of my head:
```
// Basic example of summing a value over time grouped by half hour and printing it.

func halfHourID(ds string) int {
// Business specific logic to derive an integer in range 1 - 48
// given a timestamp with timezone information included. 
}

input := `TIMESTAMP,VALUE
"Mon Jan 2 15:04:05 -0700 MST 2006",1.5
.
.
.
"Mon Jan 2 16:06:07 -0000 UTC 2006",2.25`

f := qframe.ReadCSV(strings.NewReader(input))
f = f.Apply(qframe.Instruction{Fn: halfHourID, DstCol: "HID", SrcCol1: "TIMESTAMP"})
g := qf.GroupBy(groupby.Columns("HID"))
f = g.Aggregate(qframe.Aggregation{Fn: "sum", Column: "VALUE"})
fmt.Println(f.Select("HID", "VALUE"))


HID(i)  VALUE(f)
------- --------
      1     10.5
     14   122.25
     33       23
```

This probably does not correspond exactly to what you want to achieve (perhaps not even remotely :-)) but it serves as an initial example to base further discussions on.

In general I would recommend trying to keep the data "in frame" and apply transformations and aggregations on it by using either built in functions (as "sum" above) or custom functions (like "halfHourID" above) rather than exporting it to views mid-process. Once you're done and you have the data in a shape and format that you're happy with you can export it, either by writing to a file, SQL, or just a view of some sort depending on your needs.

**Comment by tobgu** [comment]
Closing this issue since I haven't received any feedback on the above and it is too unspecific to act on. Please open a new issue, submit a PR or reopen this issue with more info if you want!
