### ISSUE TITLE
Group by not working

### ISSUE THREAD

**Issue by 2kikee122** [tobgu/qframe#19]
Hey there,

First of all - awesome library

I have the below code directly from your documents, but I keep getting this error

./main.go:14:19: undefined: groupby
compiler exit status 2

Any thoughts?

```
package main

import "fmt"
import "log"
import "os"
import "github.com/tobgu/qframe"

func main() {
  qf := qframe.New(map[string]interface{}{
      "COL1": []string{"a", "b", "a", "b", "b", "c"},
      "COL2": []float64{0.1, 0.1, 0.2, 0.4, 0.5, 0.6},
  })

  g := qf.GroupBy(groupby.Columns("COL1"))
  qf = g.Aggregate(qframe.Aggregation{Fn: "count", Column: "COL2"}).Sort(qframe.Order{Column: "COL1"})

  fmt.Println(qf)

  }
```

**Comment by tobgu** [comment]
Hi!

Thanks for checking it out!

You need to add this import for your test to work: https://github.com/tobgu/qframe/blob/master/examples_test.go#L9

The above is the file that all examples in the documentation is taken from if you need more inspiration.
