### ISSUE TITLE
Referencing columns from QF

### ISSUE THREAD

**Issue by 2kikee122** [tobgu/qframe#20]
Hey there

Thanks so much for your last response. I have one more question (sorry!!!)

I have a CSV which I ingest using the below

The problem I am having is, the names in the file are
name
age
city

But when I print f, they show like name (s), age (i)

But in the groupby I can't actually reference them like that or like they are in the file. How can I tackle that 

Thanks 
```
  f := qframe.ReadCSV(csvfile)
  fmt.Println(f)
  g := f.GroupBy(groupby.Columns("name (s)"))
  f = g.Aggregate(qframe.Aggregation{Fn: "count", Column: "age (i)"}).Sort(qframe.Order{Column: "name (s)"})
```

**Comment by tobgu** [comment]
As stated in the docs for the `String` method (https://pkg.go.dev/github.com/tobgu/qframe?tab=doc#QFrame.String) a type indicator is written in parenthesis after the column name. That should not be included when referencing the column. For aggregation, etc. So you should do:

```
g := f.GroupBy(groupby.Columns("name"))
f = g.Aggregate(qframe.Aggregation{Fn: "count", Column: "age"}).Sort(qframe.Order{Column: "name"})
```

Please include any errors (`f.Err`) as well as a snippet of the CSV if you still have problems and need further help.

**Comment by 2kikee122** [comment]
Hey thwew

I did try with just the field names too & get the error: **Columns: unknown column: "name"*

The CSV is a tiny one:

name,age,city
Bob,12,London
James,18,London
Joe,55,Manchester
Simon,21,Manchester

Thanks a lot

**Comment by kevinschoon** [comment]
You should verify your input `csvFile` is valid and that the returned qframe has no errors (`qf.Err == nil`).

Here is an example with the csv you've shared above:

```go
package main

import (
        "fmt"
        "strings"

        "github.com/tobgu/qframe"
        "github.com/tobgu/qframe/config/groupby"
)

func main() {
        input := `name,age,city
Bob,12,London
James,18,London
Joe,55,Manchester
Simon,21,Manchester`

        f := qframe.ReadCSV(strings.NewReader(input))
        g := f.GroupBy(groupby.Columns("name"))
        f = g.Aggregate(qframe.Aggregation{Fn: "count", Column: "age"}).
                Sort(qframe.Order{Column: "name"})
        fmt.Println(f.Err == nil)
        fmt.Println(f)
}
```

The program above will produces the following output:

```
true
name(s) age(i)
------- ------
    Bob      1
  James      1
    Joe      1
  Simon      1

Dims = 2 x 4
```

**Comment by tobgu** [comment]
@kevinschoon Thanks for chiming in! @2kikee122 Did that help you in your troubleshooting?

**Comment by 2kikee122** [comment]
Unfortunately, I am still stuck. But I will persist

**Comment by 2kikee122** [comment]
here is the latest code I have.

The printout of the csv is as below, I have tried both adding a space before name (as it seems to have one) and not. But neither are working - Columns: unknown column: " name"
```
 ﻿name,age,city
Bob,12,London
James,18,London
Joe,55,Manchester
Simon,21,Manchester
```

```
package main

import (
    "fmt"
    "github.com/tobgu/qframe"
    "github.com/tobgu/qframe/config/groupby"
    "io/ioutil"
    "strings"
)

func main() {
    //define filepath
    filepath := "emp.csv"

    //open the file
    openfile, _ := ioutil.ReadFile(filepath)

    //cast byte slice as string
    contents := string(openfile)

    //print contents
    fmt.Println(contents)

    f := qframe.ReadCSV(strings.NewReader(string(contents)))
    fmt.Println(f)
    
    g := f.GroupBy(groupby.Columns("name"))
    f = g.Aggregate(qframe.Aggregation{Fn: "count", Column: "age"}).
    Sort(qframe.Order{Column: " name"})
    fmt.Println(f.Err == nil)
    fmt.Println(f)

}
```

**Comment by kevinschoon** [comment]
You have an extra space in the first character of the first line of your CSV where name is:

```
 ﻿name,age,city # <--- this line
Bob,12,London
James,18,London
Joe,55,Manchester
Simon,21,Manchester
```
should be
```
name,age,city
Bob,12,London
James,18,London
Joe,55,Manchester
Simon,21,Manchester
```

**Comment by tobgu** [comment]
Completely agree with @kevinschoon, please review your input and, if you still have problems, please check the error status after each function to see exactly where things go wrong.

**Comment by 2kikee122** [comment]
Thanks - got it working. Do you guys have the ability to read XML into a dataframe?

Sorry for all the questions, just starting Golang, coming from a Python background

**Comment by kevinschoon** [comment]
Welcome to the Go community!

There is no native support for loading XML data in QFrame but I wrote an example below that should hopefully get you started.

We should probably close this issue since your original problem is solved but I would encourage you to join the [gophers](https://blog.gopheracademy.com/gophers-slack-community/) Slack team where people can help with quick questions. Feel free to message me on there as well!

```go
package main

import (
        "encoding/xml"
        "fmt"
        "strings"

        "github.com/tobgu/qframe"
)

type Data struct {
        X []float64 `xml:"X>Value"`
        Y []float64 `xml:"Y>Value"`
}

func main() {
        rawXML := `
<QFrameData>
        <X>
                <Value> 1 </Value>
                <Value> 2 </Value>
                <Value> 3 </Value>
        </X>
        <Y>
                <Value> 4 </Value>
                <Value> 5 </Value>
                <Value> 6 </Value>
        </Y>
</QFrameData>`
        data := Data{}
        err := xml.NewDecoder(strings.NewReader(rawXML)).Decode(&data)
        if err != nil {
                panic(err)
        }
        qf := qframe.New(map[string]interface{}{
                "X": data.X,
                "Y": data.Y,
        })
        fmt.Println(qf)
}
```

Output:

```
 X(f)  Y(f)
----- -----
    1     4
    2     5
    3     6

Dims = 2 x 3
```

**Comment by tobgu** [comment]
Closing this as no more input has been received.
