### ISSUE TITLE
error in READCSV 

### ISSUE THREAD

**Issue by AaamberW** [tobgu/qframe#30]
Got an error when reading from a CSV file. Same file can be read by `read_csv` function in pandas without problems. A quick visual check also confirms there's no column without a name in the file.
```
New (CheckName: column name must not be empty)
```

**Comment by tobgu** [comment]
Hi,

Please supply a minimal example that reproduces your problem, a file or a snippet. Otherwise it will be very hard to tell what the problem is.

**Comment by tobgu** [comment]
Closing this as no more info is available. Please re-open if you have an example.
