### ISSUE TITLE
Increasing Column width

### ISSUE THREAD

**Issue by hajsf** [tobgu/qframe#31]
In my dataframe, I hardly read the data in the columns, can I increase the column width so I can improve the readability?

![image](https://user-images.githubusercontent.com/46838626/93937274-20df8b00-fd30-11ea-8c51-d388423c4297.png)

**Comment by tobgu** [comment]
You cannot at the moment, the `String()` function is very much "one size fits all". I could definitely see such configurability being added to a new function, `TableString(options ...TableOption)`, or similar. That would be more configurable.

If that is something you would like to contribute Id be super happy to review a PR for it. If not it may happen anyway. I won't swear by a release date though!
