### ISSUE TITLE
Support for multiple aggregations

### ISSUE THREAD

**Issue by rogaha** [tobgu/qframe#33]
Is there a way to accomplish this? 

```
f = f.GroupBy(groupby.Columns("day")).Aggregate(
		qframe.Aggregation{Fn: sum, Column: "amount"},
		qframe.Aggregation{Fn: "count", Column: "amount"},
		qframe.Aggregation{Fn: max, Column: "amount"})
```

Error message: `Aggregate: cannot aggregate on column that is part of group by or is already an aggregate: amount`

**Comment by tobgu** [comment]
It did not, I did not have a use case for it. Does now however since it was a very easy fix. You need to supply a new, distinct, `As`, parameter in each aggregation to name the destination column. See test case here for an example: https://github.com/tobgu/qframe/blob/master/qframe_test.go#L651

**Comment by rogaha** [comment]
nicely done @tobgu, thanks for the quick fix. Congratulations for the project by the way. It has been very handy for the aggregations I'm doing in `Go`. 💯

**Comment by rogaha** [comment]
@tobgu is there a way to loop through each row in the `qframe`? I se that I can create views for each column, but this way won't be very efficient as I would need to do multiple loops through the `qframe`.

**Comment by tobgu** [comment]
Could you tell me what your high level objectives of looping over all rows is? And what do you mean by a row? Is that a `map[string]interface{}` or mapped to a struct using reflection?

In general I'd say that "exporting" all rows and looping over them is not in line with the design of qframe which is rather to keep the data "in frame" and perform operations on it there. If I can understand what you're trying to achieve I can perhaps show a good way to do it with QFrame as is. Or, there is a valid use case for exporting the data, in which case it could be considered for implementation.
