### ISSUE TITLE
Not able to read CSV with multiple empty (duplicate column names)

### ISSUE THREAD

**Issue by kp2401075** [tobgu/qframe#34]
Not able to read csv with multiple empty column names.
Expected behaviour : rename columns with numerica suffix such as empty1, empty2

example:
```csv
name, lastname , , , address
jay, patel, 12,123,12,3 na na
```

Errror
```bash
ReadCsv: Duplicate columns detected: [                       ]
```

**Comment by tobgu** [comment]
Sorry for the late response. I'd be happy to take a PR with an optional config option to ReadCSV for such functionality. I do think it should be disabled by default though since it could indicate an invalid input.

**Comment by kp2401075** [comment]
Sorry for Late reply I've been caught up in other things.

I can try and do PR, I'm not very experienced with GO so You might need to carefully review my PR and possibly suggest corrections.

If you are happy to review my PR I will start on something.

Thanks

**Comment by tobgu** [comment]
Sure! We'll work through it together to make sure it's in good shape and fits with existing code before merging. Please submit!
