### ISSUE TITLE
Unable to iterate through the GroupBy Grouper object

### ISSUE THREAD

**Issue by jahed-proj** [tobgu/qframe#35]
I need to write to different csv based on GroupBy , so I want to iterate through the GroupBy indices and write to csv. The Grouper object is not allowing to iterate through it.

Please give an example code if the functionality is present

**Comment by tobgu** [comment]
Hi! I'm not 100% sure I understand what you mean? You want to do a group by without aggregating and then extract that as a CSV? Sounds a bit like sorting on multiple columns to me?

Perhaps you could provide a minimal example (CSV before and after for example) to help me better understand?

**Comment by jahed-proj** [comment]
I need to group the data on a column using GroupBy and then Export groups in different files

Input CSV :--

DEPT,NAME,SAL
1,TOM,10
2,JERRY,30
3,SAM,55
1,HARY,99
2,JOE,66
1,KAREN,101
2,ADAM,23
3,JOHN,29
1,SHELLY,55
2,DAVID,67
3,BRAD,99
1,MICHAEL,10

 I want to group on DEPT , so the Output CSV should be.

Output:
DEPT1 .csv
DEPT,NAME,SAL
1,TOM,10
1,HARY,99
1,KAREN,101
1,SHELLY,55
1,MICHAEL,10

DEPT2.csv 
2,JERRY,30
2,JOE,66
2,ADAM,23
2,DAVID,67

and so on for DEPT3.csv

I want to GroupBy  DEPT  and write to 3 CSV. So, the f.GroupBy(groupby.Columns("DEPT"))  should give me indices for the GroupBy column and  respective DataFrames ( one for DEPT 1 , one for  DEPT 2 and one for DEPT 3) . Then I could Iterate through the Grouper object created and based on group by indices  write to respective csv.


 I was hoping to do something as below.
f := qframe.ReadCSV(csvfile)
for DEPT,data  :=  range  f.GroupBy(groupby.Columns("DEPT")) {
		fmt.Println(DEPT)
		fmt.Println(data.Select("NAME","SAL"))
		//---write to csv 
	}

We are porting our codes from python Pandas to golang , your library is of immense help . Pandas offer split-apply-combine on the groupby , so the above thing is done using pandas as 

# Export to DEPT1.csv ,DEPT2.csv, DEPT3.csv files.
for DEPT, data in df.groupby('DEPT'):
    data.to_csv("{}.csv".format(DEPT))

**Comment by tobgu** [comment]
Thanks for your input. Seems like a reasonable use case. If you want to provide a PR for it I'd be happy to review and merge that. Otherwise it may happen anyway, I just can't provide you with any guarantees of when.

A stop gap solution (which is obviously not optimal when it comes to perf but perhaps good enough) could be to use a combination of `Distinct` on DEPT to get the unique DEPTs, extract a `StringView` of the DEPT column of the new frame and iterate over that with a `Filter` on the original frame for each of the DEPT values to produce new QFrames that can then be exported to CSV.

**Comment by jahed-proj** [comment]
Thanks so much Tobias !!

The stop gap solution would work well when I have only a single column to GroupBy , but on our actual use case we might get multiple columns to groupby and the columns are dynamic in nature (column names comes from a config file) , not sure how to handle multiple columns , any direction would be helpful

**Comment by jahed-proj** [comment]
Also wondering how to iterate through your Grouper object.
I believe GroupBy returns a Grouper structure with below definition.

type Grouper struct {
	indices        []index.Int
	groupedColumns []string
	columns        []namedColumn
	columnsByName  map[string]namedColumn
	Err            error
	Stats          GroupStats
}
But when I try to access any members of the Grouper object(say indices) , it gives error as Grouper does not have that member. Does GroupBy return the above Grouper structure or the qframe.Grouper with below structure.

type Grouper struct {
	Err   error
	Stats GroupStats
	// contains filtered or unexported fields
}
so if ,
f := qframe.ReadCSV(csvfile)
newF3 := f.GroupBy(groupby.Columns("DEPT"))
NewF3 is an Grouper object ..right ?
how to iterate through or Read newF3. what is the correct structure of this object?
Thanks so much for all the help

**Comment by tobgu** [comment]
Yes, it's a Grouper object but all lower case members are private to the qframe package (that's how Go works). So you won't be able to access them directly from outside.

Regarding the stop gap solution: It should be possible to do `Distinct` on as many columns you want. Then get the `StringView`s of each of the distinct columns and loop with filter as described above.

**Comment by tobgu** [comment]
Please check the above commit for something that may help you. It was a quick thing. Hope it aligns with your needs.

**Comment by jahed-proj** [comment]
Thanks so much Tobias, you are awesome. This is of immense help to us.


Regards,
Jahedul Haque
