### ISSUE TITLE
Skip columns in CSV

### ISSUE THREAD

**Issue by pgrandinetti** [tobgu/qframe#49]
Thinking again about this: https://github.com/tobgu/qframe/pull/47
and a case can be made for having a subset of the columns in the CSV. I believe that's possible in pandas.
It may be as simple as using `>` instead of `!=` on [this line](https://github.com/tobgu/qframe/blob/master/qframe.go#L1111), but needs to be tested.

Related: It would be nice in my opinion if the interface would allow for configurations like that mentioned above to be passed as input. In other words, without changes to the internal of the package. Things like CSV configuration, JSON configuration, etc. I believe these are all functions' input in pandas.
This would require a rather large refactoring though, and, also, there are comments in the docs such as "This...should never be called outside of QFrame" (for instance, [here](https://pkg.go.dev/github.com/tobgu/qframe@v0.4.0/config/csv#NewConfig)), for which I don't know the background.

**Comment by tobgu** [comment]
For the specific use case you have I would use a `Select` (https://pkg.go.dev/github.com/tobgu/qframe#QFrame.Select) to pick the subset of columns to serialize followed by  a `ToCSV`. These operations can be chained:
```go
qf.Select(...).ToCSV(...)
```
Does this solve your needs?

Your more general suggestion is interesting, but as you say would require a bit more thought and effort.

**Comment by pgrandinetti** [comment]
Yes, chaining `Select` and `ToCSV` works.
