### ISSUE TITLE
How do you add a new column / overwrite an existing column

### ISSUE THREAD

**Issue by norandom** [tobgu/qframe#8]
Hi,

how do you overwrite a column of a `qframe` object?

I have a data-frame `qdf`.

Based on the examples I used a `view` to iterate over the column. Within the `for` loop I apply a conversion (in this case a Epoch to human-readable timestamp conversion). 

I'd like to collect all the results into the slice `presult` and add it to the columns of a new `qdf`

	view := qdf.MustStringView("EdgeStartTimestamp")
	presult := make([]string, 1)
	for i:=0; i < view.Len(); i++ {
		item := view.ItemAt(i)
		if citem, err  := strconv.Atoi(*item); err == nil {
			presult = append(presult,
				time.Unix(int64(citem) / 1000000000, 0).String())
		}
	}

I can apply functions to one column, but I cannot add a new column:

`qdf = qdf.Apply(qframe.Instruction{Fn: function.IntF, DstCol: "EdgeStartTimestamp", SrcCol1: "EdgeStartTimestamp" })`

In this particular case I convert the column `EdgeStartTimestamp`. My goal would be to have a column `timestamp` with the contents of `"EdgeStartTimestamp"` in the replaced `qdf` object.

Is there a way to do this at the moment?

Best,
Marius

**Comment by tobgu** [comment]
Hi Marius,

Given my understanding of what you want to do, here's how I would do it:
```go
qf := qframe.New(map[string]interface{}{
	"ints":    []int{1, 2},
})

converter := func(x int) *string {
	result := strconv.Itoa(x)
	return &result
}

// This will give you a new qframe with both ints and strings
qf2 := qf.Apply(qframe.Instruction{Fn: converter, DstCol: "strings", SrcCol1: "ints"})

// In the above example, if you wanted to overwrite the ints column directly
// you could just give it as DstCol. 
	
// If you just want to keep the strings column you can just drop the ints column
qf3 := qf2.Drop("ints")
```

Let me know if this solves your particular problem. If not please elaborate on what you want to do.

**Comment by norandom** [comment]
Thank you for your reply, and sorry for my late response. 

This solved my issue.

For reference:

```
	qdf = qdf.Apply(qframe.Instruction{Fn: function.IntF, DstCol: "EdgeStartTimestamp", SrcCol1: "EdgeStartTimestamp" })
	fmt.Println(qdf.Select("ClientIP", "EdgeStartTimestamp", "ClientRequestHost"))
```

> ClientIP(s) EdgeStartTimestamp(i) ClientRequestHost(s)
> ----------- --------------------- --------------------
> 1234:df:...   1538467248904000000       test.com
> 

Now the Integer column EdgeStartTimeStamp gets converted to a time-stamp (human readable)

```
	timestamp_converter := func(x int) *string {
		result := time.Unix(int64(x) / 1000000000, 0).String()
		return &result
	}

	qf2 := qdf.Apply(qframe.Instruction{Fn: timestamp_converter, DstCol: "New_Column", SrcCol1: "EdgeStartTimestamp"})
	fmt.Println(qf2)
```

Seems to work:

> ClientIP(s) New_Column(s)
> ----------- -------------
> 123.12.1... 2018-10-02...

I just need to figure out how to print the entire column ... However in this case the (s) already indicates the successful conversion and I can see it when I dump the df.
